#Basic Window Settings
WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 720
MIN_WINDOW_WIDTH = 600
WINDOW_TITLE = 'ZHELTA'
ICON = './icons/icon.ico'
X_RESIZE_WINDOW = True
Y_RESIZE_WINDOW = False
#Digital Frame Settings
DIGITAL_FRAME_BACKGROUND = '#a19e9d'
RELHEIGHT_DIGITAL_FRAME = 0.3
#Functional Frame Settings
FUNCTIONAL_FRAME_BACKGROUND = '#cfcbca'
RELHEIGHT_FUNCTIONAL_FRAME = 1 - RELHEIGHT_DIGITAL_FRAME # Do not change!
#Button to search for JSON file 
TEXT_SEARCH_BUTTON = 'drag or search for .json file'
BACKGROUND_SEARCH_BUTTON = '#567'
ACTIVEBACKGROUND_SEARCH_BUTTON = '#345'
FOREGROUND_SEARCH_BUTTON = '#fff'
HEIGHT_SEARCH_BUTTON = 5
WIDTH_SEARCH_BUTTON = 40
PADY_SEARCH_BUTTON = 50